name: Star all repos
on:
  issues:
    types: [opened]
jobs:
  star:
    runs-on: ubuntu-latest
    environment: star-all-repos
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run star
      env:
        REPO_OWNER: ${{github.repository_owner}}
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        AUTH_CODE: ${{github.event.issue.title}}
